name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"  # Reemplaza con tu ID de proyecto de Google Cloud
  REGION: "${{ secrets.REGION }}"           # Reemplaza con tu región
  SERVICE: "${{ secrets.SERVICE_NAME }}"    # Reemplaza con el nombre de tu servicio de Cloud Run

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'  # Acción para hacer checkout del repositorio

      - name: 'Authenticate with Google Cloud'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}  # El secreto con el JSON de la cuenta de servicio
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
          gcloud config set project ${{ env.PROJECT_ID }}

      - name: 'Build and Push Docker Image'
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}" \
            --region ${{ env.REGION }} \
            --platform managed

      - name: 'Show Deployed URL'
        run: |
          echo "Deployed URL: https://${{ env.SERVICE }}.${{ env.REGION }}.run.app"
