name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: '${{ secrets.PROJECT_ID }}' # ID del proyecto en Google Cloud
  REGION: '${{ secrets.REGION }}'        # Región (e.g., us-central1)
  SERVICE: '${{ secrets.SERVICE }}'      # Nombre del servicio en Cloud Run
  WORKLOAD_IDENTITY_PROVIDER: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}' # Proveedor de identidad

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Paso 1: Checkout del código
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Paso 2: Autenticación con Google Cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'

      # Paso 3: Login en Docker
      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      # Paso 4: Build y push de la imagen
      - name: 'Build and Push Container'
        run: |-
          # Sanitizar las variables de entorno
          echo "Original REGION: '${{ env.REGION }}'"
          REGION="${{ env.REGION }}" && REGION="${REGION// /}"
          PROJECT_ID="${{ env.PROJECT_ID }}" && PROJECT_ID="${PROJECT_ID// /}"
          SERVICE="${{ env.SERVICE }}" && SERVICE="${SERVICE// /}"

          # Validar las variables
          if [[ -z "${REGION}" ]]; then
            echo "Error: REGION is not set or empty."
            exit 1
          fi

          # Construir el tag de Docker
          DOCKER_TAG="${REGION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE}:${{ github.sha }}"
          echo "Generated DOCKER_TAG: ${DOCKER_TAG}"

          # Validar el formato del tag
          if [[ ! "${DOCKER_TAG}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+:[a-zA-Z0-9._-]+$ ]]; then
            echo "Error: Invalid DOCKER_TAG format: ${DOCKER_TAG}"
            exit 1
          fi

          # Construir y empujar la imagen
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      # Paso 5: Desplegar en Cloud Run
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'

      # Paso 6: Mostrar la URL del servicio
      - name: 'Show output'
        run: |2-

          echo ${{ steps.deploy.outputs.url }}
